import './globals.css'
import ThemeRegistry from '@/theme/ThemeRegistry'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/store/ReduxProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ThemeRegistry>
          <body className={inter.className}>{children}</body>
        </ThemeRegistry>
      </ReduxProvider>
    </html>
  )
}
